version: '3.8'

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=dev@js.wiki
      - PGADMIN_DEFAULT_PASSWORD=123123
      - PGADMIN_DISABLE_POSTFIX=True
      - PGADMIN_LISTEN_PORT=8000
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    ports:
      - "8000:8000"

volumes:
  postgres-data:
