defaultSemverRangePrefix: ''

enableTelemetry: false

nodeLinker: node-modules

packageExtensions:
  'rollup-plugin-visualizer@*':
    dependencies:
      'rollup': '*'
  'v-network-graph@*':
    dependencies:
      'd3-force': '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-3.2.0.cjs
