# -- DEV DOCKER-COMPOSE --
# -- DO NOT USE IN PRODUCTION! --

version: "3.8"
services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@js.wiki
      PGADMIN_DEFAULT_PASSWORD: "123123"
      PGADMIN_DISABLE_POSTFIX: true
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: False
    network_mode: service:db
    logging:
      driver: "none"

  wiki:
    build:
      context: ../..
      dockerfile: dev/containers/Dockerfile
    command: sleep infinity
    depends_on:
      - db
    volumes:
      - ../..:/workspace
    network_mode: service:db
    ipc: host
    init: true


volumes:
  db-data:
